---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[loganov-jenkins::default]
    attributes:
  - name: pipeline-chef
    run_list:
      - recipe[loganov-jenkins::pipeline_chef]
    attributes: